select
    calibration_id,
    gauge_id,
    cast(due_date as date) as due_date,
    cast(pulled_date as date) as pulled_date,
    cast(done_date as date) as done_date,
    cast(returned_date as date) as returned_date,
    result,
    cast(tolerance as double) as tolerance,
    cast(check_point_1 as double) as check_point_1,
    cast(as_found_error_1 as double) as as_found_error_1,
    cast(as_left_error_1 as double) as as_left_error_1,
    cast(check_point_2 as double) as check_point_2,
    cast(as_found_error_2 as double) as as_found_error_2,
    cast(as_left_error_2 as double) as as_left_error_2,
    cast(check_point_3 as double) as check_point_3,
    cast(as_found_error_3 as double) as as_found_error_3,
    cast(as_left_error_3 as double) as as_left_error_3,
    cast(check_point_4 as double) as check_point_4,
    cast(as_found_error_4 as double) as as_found_error_4,
    cast(as_left_error_4 as double) as as_left_error_4,
    cast(check_point_5 as double) as check_point_5,
    cast(as_found_error_5 as double) as as_found_error_5,
    cast(as_left_error_5 as double) as as_left_error_5,
    reference_standard,
    performed_by,
    performed_by_id,
    certificate_no,
    export_batch_id
from {{ source('calibration', 'calibration__calibrations') }}
