select
    characteristic_id,
    part_id,
    revision,
    characteristic_name,
    characteristic_type,
    cast(nominal as double) as nominal,
    cast(usl as double) as usl,
    cast(lsl as double) as lsl,
    unit,
    cast(critical_flag as boolean) as critical_flag,
    cast(customer_designated_flag as boolean) as customer_designated_flag,
    gauge_id,
    cast(subgroup_size as integer) as subgroup_size,
    frequency,
    inspection_method,
    cast(chart_centre as double) as chart_centre,
    cast(chart_ucl as double) as chart_ucl,
    cast(chart_lcl as double) as chart_lcl,
    cast(range_ucl as double) as range_ucl,
    created_by,
    created_at,
    modified_at,
    export_batch_id
from {{ source('qms', 'qms__characteristics') }}
